ALTER TABLE Cities
ADD CONSTRAINT PK_CityId PRIMARY KEY (Id),
ADD CONSTRAINT UQ_CityName UNIQUE (CityName);

ALTER TABLE Companies
ADD CONSTRAINT PK_CompanyId PRIMARY KEY (Id),
ADD CONSTRAINT UQ_CompanyName UNIQUE (CompanyName);

ALTER TABLE Guests
ADD CONSTRAINT PK_GuestId PRIMARY KEY (Id),
ADD CONSTRAINT UQ_Phone UNIQUE (Phone);


ALTER TABLE Hotels
ADD CONSTRAINT PK_HotelId PRIMARY KEY (Id),
ADD CONSTRAINT FK_CityId FOREIGN KEY (CityId) REFERENCES Cities (Id),
ADD CONSTRAINT FK_CompanyId FOREIGN KEY (CompanyId) REFERENCES Companies (Id);

ALTER TABLE Rooms
ADD CONSTRAINT PK_RoomId PRIMARY KEY (Id),
ADD CONSTRAINT FK_HotelId FOREIGN KEY (HotelId) REFERENCES Hotels (Id),
ADD CONSTRAINT CK_Cost CHECK (Rooms.Cost::decimal > 0::decimal);

ALTER TABLE Bookings
ADD CONSTRAINT PK_BookingId PRIMARY KEY (Id),
ADD CONSTRAINT FK_RoomId FOREIGN KEY (RoomId) REFERENCES Rooms (Id),
ADD CONSTRAINT FK_GuestId FOREIGN KEY (GuestId) REFERENCES Guests (Id);
